use_frameworks!

target 'ExtFoundation_Example' do
  pod 'ExtFoundation', :path => '../'

  target 'ExtFoundation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
